name: Issue Form Pipeline

# Evento que irá acionar a pipeline
on:
  issues:
    types: [opened, reopened]

jobs:
  FormTests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - name: Show parsed data JSON
        run: |
          echo "${{ steps.parse.outputs.payload }}"
